version: '2'
services:
  probusca_server:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./probusca
    ports: 
      - "7755:3000"
    volumes:
      - ./probusca:/probusca
    container_name: probusca_server
    depends_on:
      - probusca_api
    entrypoint: ["npm", "run", "dev"]

  probusca_api:
    expose:
      - "7700"
    volumes:
      - ./backend:/backend
    container_name: probusca_api
    build:
      context: ./backend
    ports:
      - "7700:7700"

  nginx:
    image: nginx:1.17.10
    depends_on:
      - probusca_server
      - probusca_api
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 7777:7777

  tests:
    image: cypress/included:10.0.0
    container_name: probusca_tests
    working_dir: /tests
    volumes:
      - ./tests:/tests
    depends_on:
      - nginx
